auth {
    pam {
        enabled = true
        module = hyprlock
    }

    fingerprint {
        enabled = true
    }
}

# =========================
# BACKGROUND
# =========================

background {
    monitor =
    path = $HOME/.config/hypr/wallpaper.png

    blur_passes = 3
    blur_size = 8

    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
}

# =========================
# TIME
# =========================

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M:%S')"

    font_family = CodeNewRoman Nerd Font Mono
    font_size = 96
    color = rgb(cdd6f4)

    position = 0, 180
    halign = center
    valign = center
}

# =========================
# DATE
# =========================

label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %-d %B')"

    font_family = Inter
    font_size = 24
    color = rgb(a6adc8)

    position = 0, 80
    halign = center
    valign = center
}

# =========================
# PASSWORD
# =========================

input-field {
    monitor =

    size = 300, 54
    outline_thickness = 1

    dots_size = 0.20
    dots_spacing = 0.28

    outer_color = rgba(cdd6f433)
    inner_color = rgba(17, 17, 27, 0.55)
    font_color = rgb(cdd6f4)

    fade_on_empty = false
    placeholder_text = Password

    position = 0, -100
    halign = center
    valign = center
}
