background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.3

    outer_color = rgba(ffffffaa)
    inner_color = rgba(00000055)
    font_color = rgb(ffffff)

    fade_on_empty = false
    placeholder_text = <i>Password...</i>

    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    font_size = 64

    position = 0, 100
    halign = center
    valign = center
}
